### ISSUE TITLE
Some minor errors in Level 2 Project

### ISSUE THREAD

**Issue by bruno-ponne** [PacktPublishing/Master-SQL-for-Data-Analysis#1]
Hello, thanks a lot for this course! It was very helpful. I would like to point out two minor errors in the Level 2 Project pdfs:

- [ ] _Exercise #14 Create a view called “customers_shipped_vw” for all customers (customer id, customer name,
customer city, order status) with orders that are in “shipping” status_. - It should read "shipped" instead of "shipping";

- [ ] Solution of Exercise # 4 - _WHERE price > 4000 should_ be **WHERE price > 3000**

**Comment by Sonakshis** [comment]
Hi 
Thank you for highlighting this issue! Your feedback is greatly appreciated and has led us to update our resources accordingly.
https://github.com/PacktPublishing/Master-SQL-for-Data-Analysis/tree/9eafb56004aff00c75a1bc037b14e0f98b2fc128/Level%202%20Resources/Level%202%20Project
